package saber

// En devuelve la nota en el idioma pedido. Para "en" busca la traduccion
// por el texto espanol de Que; si no la hay, cae al espanol -mejor decir
// algo cierto en otro idioma que callar-. El catalogo (saber.go) sigue
// siendo la fuente unica: aqui solo se traduce lo que ya existe alli.
func (n Nota) En(idioma string) Nota {
	if idioma != "en" {
		return n
	}
	t, ok := traduccionesEn[n.Que]
	if !ok {
		return n
	}
	if t.Por == "" {
		t.Por = n.Por
	}
	return t
}

// traduccionesEn empareja cada Que espanol con su nota en ingles. La clave
// es el Que espanol tal cual aparece en el catalogo; si alli cambia, hay
// que cambiarlo aqui (o se sirve el espanol como respaldo).
var traduccionesEn = map[string]Nota{
	"SDK de camaras IP Hikvision y Dahua": {"Hikvision and Dahua IP-camera SDK", "they hunt for exposed video surveillance to recruit into a botnet"},
	"protocolo ONVIF de camaras de red": {"ONVIF network-camera protocol", "they scan for cameras to peek at or hijack"},
	"captura de imagen de camaras IP": {"IP-camera snapshot", "they check whether the camera responds without asking for a password"},
	"fichero de entorno de Laravel, Django y similares": {"environment file for Laravel, Django and the like", "it usually holds database passwords and API keys"},
	"repositorio Git expuesto": {"exposed Git repository", "with it they download the whole source code, history included"},
	"credenciales de Amazon Web Services": {"Amazon Web Services credentials", "they give direct access to the bill and the cloud data"},
	"clave SSH privada": {"private SSH key", "with it they get in with no password needed"},
	"directorio de claves SSH": {"SSH keys directory", "they look for private keys or to drop their own in authorized_keys"},
	"copias de seguridad accesibles": {"accessible backups", "a database dump saves them from having to break in"},
	"panel de WordPress": {"WordPress admin panel", "they try the manager's credentials"},
	"entrada de WordPress": {"WordPress login", "brute force against the manager"},
	"XML-RPC de WordPress": {"WordPress XML-RPC", "it lets them try thousands of passwords in a single request"},
	"phpMyAdmin": {"phpMyAdmin", "direct access to the database"},
	"gestor de Apache Tomcat": {"Apache Tomcat manager", "from there they deploy their own app, which means running code"},
	"Apache Solr": {"Apache Solr", "service with known remote-code-execution flaws"},
	"endpoints de Spring Boot Actuator": {"Spring Boot Actuator endpoints", "they expose configuration and sometimes cleartext credentials"},
	"intento de Log4Shell (CVE-2021-44228)": {"Log4Shell attempt (CVE-2021-44228)", "runs code just by getting the server to log the text"},
	"PHPUnit expuesto (CVE-2017-9841)": {"exposed PHPUnit (CVE-2017-9841)", "runs arbitrary PHP code; still one of the most profitable"},
	"CGI clasico": {"classic CGI", "probing for Shellshock and old router panels"},
	"servidor Boa de routers domesticos": {"Boa server of home routers", "they look for routers with the factory password"},
	"HNAP de routers D-Link": {"D-Link routers' HNAP", "known remote-administration flaw"},
	"routers GPON de fibra": {"GPON fiber routers", "a 2018 flaw that still recruits thousands of devices"},
	"acceso directo a una shell": {"direct shell access", "they test whether a door is open"},
	"icono del navegador": {"browser icon", "any browser requests it on its own; not an attack"},
	"fichero para buscadores": {"file for search engines", "requested both by legitimate crawlers and by whoever is mapping the site"},
	"descarga de un programa desde fuera": {"downloading a program from outside", "the step where an intrusion turns into an infection"},
	"descarga por TFTP": {"TFTP download", "common on IoT gear, which ships without wget or curl"},
	"BusyBox": {"BusyBox", "an unmistakable IoT-botnet sign: Mirai and its variants use it"},
	"dar permiso de ejecucion": {"granting execute permission", "they prepare the just-downloaded file to launch it"},
	"permisos totales sobre un fichero": {"full permissions on a file", "the same, brute-force style"},
	"fichero de contrasenas cifradas": {"hashed-password file", "they take it to crack it at leisure elsewhere"},
	"lista de usuarios del sistema": {"system user list", "reconnaissance: whom they can impersonate"},
	"version del sistema": {"system version", "they pick which exploit and binary will work"},
	"caracteristicas del procesador": {"CPU details", "usually measured before installing a crypto miner"},
	"numero de nucleos": {"core count", "they size the machine, a typical prelude to mining"},
	"tarea programada": {"scheduled task", "persistence: they want to come back after a reboot"},
	"clave SSH propia anadida": {"their own SSH key added", "a backdoor that survives a password change"},
	"creacion de un usuario": {"creating a user", "they build their own way in"},
	"cambio de contrasena": {"password change", "they lock the owner out of their own machine"},
	"borrado de las reglas de cortafuegos": {"wiping the firewall rules", "they clear the way for what comes next"},
	"cortafuegos desactivado": {"firewall disabled", "they clear the way"},
	"borrado del historial de comandos": {"clearing the command history", "they cover up what they just did"},
	"borrado de los registros": {"wiping the logs", "they cover up what they just did"},
	"comando de RouterOS de MikroTik": {"MikroTik RouterOS command", "they check whether they landed on a MikroTik router"},
	"memoria disponible": {"available memory", "they size the machine"},
	"Censys, inventario publico de internet": {"Censys, a public internet inventory", "they scan the whole internet for research; they're not after you"},
	"Shodan, buscador de dispositivos conectados": {"Shodan, a search engine for connected devices", "they scan the whole internet; their visit isn't an attack"},
	"Shadowserver, fundacion de seguridad sin animo de lucro": {"Shadowserver, a non-profit security foundation", "they scan to warn the owners of vulnerable devices"},
	"BinaryEdge, inventario de internet": {"BinaryEdge, an internet inventory", "research scanning"},
	"Rapid7, proyecto Sonar": {"Rapid7, the Sonar project", "research scanning"},
	"Internet Measurement, escaneo academico": {"Internet Measurement, academic scanning", "research scanning"},
	"Driftnet, inventario de internet": {"Driftnet, an internet inventory", "research scanning"},
	"DigitalOcean": {"DigitalOcean", "cheap, high-churn hosting: a common source of hostile scanning"},
	"Vultr": {"Vultr", "cheap hosting: a common source of hostile scanning"},
	"Linode": {"Linode", "cheap hosting: a common source of hostile scanning"},
	"Hetzner": {"Hetzner", "cheap hosting: a common source of hostile scanning"},
	"OVH": {"OVH", "cheap hosting: a common source of hostile scanning"},
	"ChinaNet": {"ChinaNet", "one of the networks with the most scan traffic in the world"},
	"Cloudflare": {"Cloudflare", "it's a middleman: the IP doesn't identify who is behind it"},
	"red Tor": {"the Tor network", "the real origin is hidden behind the anonymity network"},
	"ZGrab, escaner de internet a gran escala": {"ZGrab, a large-scale internet scanner", "mass sweep; they're not after you in particular"},
	"Masscan": {"Masscan", "mass port sweep"},
	"Nmap": {"Nmap", "port and service scanning"},
	"Censys": {"Censys", "a public internet inventory, not hostile"},
	"Shodan": {"Shodan", "a public internet inventory, not hostile"},
	"Paramiko, libreria SSH de Python": {"Paramiko, Python's SSH library", "there's a script behind it, not a person"},
	"libssh": {"libssh", "there's an automated tool behind it"},
	"cliente SSH escrito en Go": {"an SSH client written in Go", "a custom tool; common in modern scanners"},
	"curl": {"curl", "an automated request"},
	"wget": {"wget", "an automated request"},
	"libreria requests de Python": {"Python's requests library", "there's a script behind it"},
	"navegador": {"a browser", "it's a real browser; it could be a person watching"},
	"credencial de fabrica de camaras XiongMai": {"XiongMai camera factory credential", "it's in the Mirai source code"},
	"credencial de fabrica de camaras Dahua": {"Dahua camera factory credential", "it's in the Mirai source code"},
	"credencial de fabrica de grabadores Dahua": {"Dahua DVR factory credential", "it's in the Mirai source code"},
	"credencial de fabrica de grabadores": {"DVR factory credential", "it's in the Mirai source code"},
	"credencial de fabrica": {"factory credential", "Mirai dictionary"},
	"credencial por defecto universal": {"universal default credential", "the first thing any bot tries"},
	"credencial por defecto de routers": {"router default credential", "the first thing any bot tries"},
	"credencial de fabrica de routers": {"router factory credential", "Mirai dictionary"},
	"credencial por defecto de Raspberry Pi": {"Raspberry Pi default credential", "they hunt for unconfigured Raspberry Pis"},
	"credencial de fabrica de Ubiquiti": {"Ubiquiti factory credential", "they hunt for Ubiquiti radios and routers"},
	"cambio de configuracion en caliente": {"live configuration change", "the first step of Redis's classic path to write someone else's file to disk, like an SSH key or a cron job"},
	"carga de un modulo nativo": {"loading a native module", "it's direct code execution on the server"},
	"replicacion desde otro servidor": {"replication from another server", "used to make Redis load whatever the attacker's machine sends"},
	"ejecucion de un script Lua": {"running a Lua script", "runs code inside the server"},
	"borrado de todos los datos": {"wiping all data", "destructive; usually goes with a ransom hijack"},
	"borrado de la base de datos": {"wiping the database", "destructive"},
	"volcado a disco": {"dump to disk", "together with CONFIG SET it decides where the file is written"},
	"comando de depuracion de Redis": {"Redis debug command", "some can bring the server down"},
	"comprobacion de que el servicio responde": {"checking the service responds", "the first step of any automated inventory"},
	"version y estado del servidor": {"server version and status", "that's how they find out whether the version has known flaws"},
	"lista de comandos disponibles": {"list of available commands", "service reconnaissance"},
	"lectura de la configuracion": {"reading the configuration", "they look at how it's set up, still without touching anything"},
	"numero de claves guardadas": {"number of stored keys", "they gauge whether the database has content"},
	"informacion de conexiones": {"connection information", "reconnaissance"},
	"prueba de eco": {"echo test", "they check they're really speaking Redis"},
	"hora del servidor": {"server time", "reconnaissance"},
	"cierre ordenado de la conexion": {"orderly connection close", "polite scanners do it; an attacker rarely says goodbye"},
	"comando inexistente a proposito": {"a deliberately nonexistent command", "they trigger an error to fingerprint the server by how it complains; it's the signature of an automated inventory"},
	"ejecucion de un programa via FTP": {"running a program via FTP", "an old flaw that gives code execution"},
	"subida de un fichero": {"uploading a file", "they upload something to the server, not just look"},
	"borrado de un fichero": {"deleting a file", "destructive"},
	"identificacion de usuario": {"user identification", "reconnaissance"},
	"tipo de sistema operativo": {"operating-system type", "they find out what's behind it before choosing the exploit"},
	"funciones que admite el servidor": {"features the server supports", "reconnaissance"},
	"listado de directorio": {"directory listing", "they look at what's there"},
	"comprobacion de que el puerto esta abierto": {"checking the port is open", "the first step of any automated inventory; they never actually tried anything against the service"},
	"intento de usar el servidor como pasarela": {"attempt to use the server as a relay", "they're not after your data, they want your connection to hide theirs: spam, brute force against third parties, or traffic they don't want leaving their own IP"},
}
